[package]
name = "soloopsctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
clap.workspace = true
rand.workspace = true
rpassword.workspace = true
soloops-server = { path = "../../crates/soloops-server" }
soloops-storage = { path = "../../crates/soloops-storage" }
tokio.workspace = true
